import React from 'react'
import { motion } from 'framer-motion'
import { Download, Printer, Shield, AlertTriangle, CheckCircle2, FileText } from 'lucide-react'
import { useClaimStore } from '@/store/useClaimStore'
import { getRecommendationDisplay, getRiskColorClasses, formatCurrency } from '@/lib/utils'

interface ReportExportPDFProps {}

export const ReportExportPDF: React.FC<ReportExportPDFProps> = () => {
  const { report, currentClaimForm } = useClaimStore()

  if (!report) return null

  const recDisplay = getRecommendationDisplay(
    report.final_recommendation || report.recommended_action
  )

  const handlePrint = () => window.print()

  const handleDownload = () => {
    // Create a formatted text report for download
    const content = generateTextReport(report, currentClaimForm)
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `ClaimGuard_Report_${report.claim_id}_${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-5">
      {/* Report Preview Card */}
      <div className="premium-card p-5 space-y-4" id="report-preview">
        <div className="flex items-center gap-2 pb-3 border-b border-gray-100">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
            <Shield size={16} className="text-white" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-gray-900">ClaimGuard AI — Adversarial Review Report</h3>
            <p className="text-xs text-gray-500 font-mono">Generated: {new Date().toLocaleString()}</p>
          </div>
        </div>

        {/* Key info */}
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: 'Claim ID', value: report.claim_id, mono: true },
            { label: 'Risk Level', value: report.risk_level || report.overall_risk_level },
            { label: 'Overall Score', value: `${report.overall_risk_score}/100`, mono: true },
            { label: 'Fraud Score', value: report.fraud_score ? `${report.fraud_score}/100` : 'N/A', mono: true },
          ].map(({ label, value, mono }) => (
            <div key={label} className="bg-gray-50 rounded-xl p-3">
              <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">{label}</p>
              <p className={`text-sm font-bold text-gray-800 ${mono ? 'font-mono' : ''}`}>{value}</p>
            </div>
          ))}
        </div>

        {/* Recommendation banner */}
        <div className={`rounded-xl p-3 border ${recDisplay.bg} flex items-center gap-3`}>
          <AlertTriangle size={16} className={recDisplay.textColor} />
          <div>
            <p className="text-xs font-semibold text-gray-600">Final Recommendation</p>
            <p className={`text-sm font-bold ${recDisplay.textColor}`}>
              {report.final_recommendation || report.recommended_action}
            </p>
          </div>
        </div>

        {/* Evidence summary */}
        {report.key_evidence && report.key_evidence.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
              Key Evidence ({report.key_evidence.length})
            </p>
            <ul className="space-y-1.5">
              {report.key_evidence.map((ev, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-gray-600">
                  <span className="text-red-400 flex-shrink-0 mt-0.5">•</span>
                  {ev}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Questions */}
        {report.investigator_questions && report.investigator_questions.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
              Investigator Questions ({report.investigator_questions.length})
            </p>
            <ul className="space-y-1.5">
              {report.investigator_questions.map((q, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-gray-600">
                  <span className="text-blue-500 font-mono font-bold flex-shrink-0">{i + 1}.</span>
                  {q}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Disclaimer */}
        <div className="flex items-start gap-2 p-3 bg-amber-50 border border-amber-100 rounded-xl">
          <CheckCircle2 size={13} className="text-amber-600 flex-shrink-0 mt-0.5" />
          <p className="text-[10px] text-amber-700 leading-relaxed">
            This report is generated by an AI system for investigator assistance only. All decisions must be reviewed and confirmed by a licensed insurance professional. Adversarial prompt injection defense was active during analysis.
          </p>
        </div>
      </div>

      {/* Export Buttons */}
      <div className="flex flex-col gap-2.5">
        <motion.button
          onClick={handlePrint}
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.99 }}
          className="btn-primary justify-center py-3 w-full"
          id="print-report-btn"
        >
          <Printer size={16} />
          Print Report
        </motion.button>
        <motion.button
          onClick={handleDownload}
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.99 }}
          className="btn-secondary justify-center py-3 w-full"
          id="download-report-btn"
        >
          <Download size={16} />
          Download Text Report
        </motion.button>
      </div>
    </div>
  )
}

function generateTextReport(report: ReturnType<typeof useClaimStore.getState>['report'], form: ReturnType<typeof useClaimStore.getState>['currentClaimForm']): string {
  if (!report) return ''
  const separator = '='.repeat(60)
  const lines = [
    'CLAIMGUARD AI — ADVERSARIAL CLAIMS REVIEW REPORT',
    separator,
    `Generated: ${new Date().toLocaleString()}`,
    `Claim ID: ${report.claim_id}`,
    `Overall Risk Score: ${report.overall_risk_score}/100`,
    `Risk Level: ${report.risk_level || report.overall_risk_level}`,
    `Fraud Score: ${report.fraud_score ?? 'N/A'}`,
    separator,
    'FINAL RECOMMENDATION:',
    report.final_recommendation || report.recommended_action || 'N/A',
    separator,
    'KEY EVIDENCE:',
    ...(report.key_evidence || []).map((e, i) => `${i + 1}. ${e}`),
    separator,
    'INVESTIGATOR QUESTIONS:',
    ...(report.investigator_questions || []).map((q, i) => `${i + 1}. ${q}`),
    separator,
    'DISCLAIMER: AI-generated report for investigator assistance only.',
    'All decisions require confirmation by a licensed insurance professional.',
  ]
  return lines.join('\n')
}
