"""
app/api/v1/endpoints/claims.py

Claims Management endpoints + document upload endpoint.
All business logic is delegated to ClaimService and DocumentService.
"""
from __future__ import annotations

import time

from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logging import logger
from app.db.session import get_db
from app.schemas.claim import (
    ClaimDetailResponse,
    ClaimListResponse,
    ClaimStatus,
    CreateClaimRequest,
    CreateClaimResponse,
    DeleteClaimResponse,
    UpdateClaimRequest,
    UpdateClaimResponse,
)
from app.schemas.document import DocumentUploadResponse
from app.services.claim_service import ClaimService
from app.services.document_service import DocumentService
from app.services.ocr_service import OCRError
from app.services.pdf_extraction_service import PDFExtractionError

router = APIRouter(prefix="/claims", tags=["Claims"])

_MAX_BYTES = settings.MAX_UPLOAD_SIZE_MB * 1024 * 1024


# ── Dependency factories ──────────────────────────────────────────────────────

def get_claim_service() -> ClaimService:
    return ClaimService()


def get_document_service() -> DocumentService:
    return DocumentService()


# ── POST /claims ──────────────────────────────────────────────────────────────

@router.post(
    "",
    response_model=CreateClaimResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new claim",
)
async def create_claim(
    payload: CreateClaimRequest,
    db: AsyncSession = Depends(get_db),
    svc: ClaimService = Depends(get_claim_service),
) -> CreateClaimResponse:
    """Create a new insurance claim.

    - claim_number must be unique.
    - claimed_amount must be > 0.
    - Status defaults to PENDING.
    - UUID is generated by PostgreSQL.
    """
    start = time.perf_counter()
    try:
        claim = await svc.create_claim(payload, db)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc))
    except Exception as exc:
        logger.error("create_claim failed | %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create claim.",
        )

    logger.info(
        "POST /claims | claim_id=%s | elapsed_ms=%d",
        claim.claim_id, int((time.perf_counter() - start) * 1000),
    )
    return CreateClaimResponse(
        success=True,
        claim_id=str(claim.claim_id),
        claim_number=claim.claim_number,
        status=claim.status,
        message="Claim created successfully.",
    )


# ── GET /claims ───────────────────────────────────────────────────────────────

@router.get(
    "",
    response_model=ClaimListResponse,
    status_code=status.HTTP_200_OK,
    summary="List all claims",
)
async def list_claims(
    page: int = Query(1, ge=1, description="Page number (1-based)"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
    search: str | None = Query(None, description="Search claim_number, claimant_name, policy_number"),
    status_filter: ClaimStatus | None = Query(None, alias="status", description="Filter by status"),
    claim_type: str | None = Query(None, description="Filter by claim type"),
    sort_by: str = Query("created_at", description="Sort field"),
    sort_order: str = Query("desc", pattern="^(asc|desc)$", description="asc or desc"),
    db: AsyncSession = Depends(get_db),
    svc: ClaimService = Depends(get_claim_service),
) -> ClaimListResponse:
    """Return a paginated list of claims with optional filtering and sorting."""
    return await svc.list_claims(
        db,
        page=page,
        page_size=page_size,
        search=search,
        status=status_filter,
        claim_type=claim_type,
        sort_by=sort_by,
        sort_order=sort_order,
    )


# ── GET /claims/{claim_id} ────────────────────────────────────────────────────

@router.get(
    "/{claim_id}",
    response_model=ClaimDetailResponse,
    status_code=status.HTTP_200_OK,
    summary="Get a claim with its documents",
)
async def get_claim(
    claim_id: str,
    db: AsyncSession = Depends(get_db),
    svc: ClaimService = Depends(get_claim_service),
) -> ClaimDetailResponse:
    """Return a single claim with all linked document metadata.

    OCR text is NOT included in the response.
    """
    try:
        return await svc.get_claim(claim_id, db)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc))


# ── PUT /claims/{claim_id} ────────────────────────────────────────────────────

@router.put(
    "/{claim_id}",
    response_model=UpdateClaimResponse,
    status_code=status.HTTP_200_OK,
    summary="Update a claim",
)
async def update_claim(
    claim_id: str,
    payload: UpdateClaimRequest,
    db: AsyncSession = Depends(get_db),
    svc: ClaimService = Depends(get_claim_service),
) -> UpdateClaimResponse:
    """Update mutable claim fields.

    Immutable fields (claim_id, claim_number, created_at) are ignored.
    At least one field must be provided.
    """
    try:
        claim = await svc.update_claim(claim_id, payload, db)
    except ValueError as exc:
        detail = str(exc)
        code = (
            status.HTTP_400_BAD_REQUEST
            if "No updatable" in detail
            else status.HTTP_404_NOT_FOUND
        )
        raise HTTPException(status_code=code, detail=detail)
    except Exception as exc:
        logger.error("update_claim failed | claim_id=%s | %s", claim_id, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update claim.",
        )

    return UpdateClaimResponse(
        success=True,
        claim_id=str(claim.claim_id),
        status=claim.status,
        message="Claim updated successfully.",
    )


# ── DELETE /claims/{claim_id} ─────────────────────────────────────────────────

@router.delete(
    "/{claim_id}",
    response_model=DeleteClaimResponse,
    status_code=status.HTTP_200_OK,
    summary="Delete a claim and all related data",
)
async def delete_claim(
    claim_id: str,
    db: AsyncSession = Depends(get_db),
    svc: ClaimService = Depends(get_claim_service),
) -> DeleteClaimResponse:
    """Delete a claim and cascade-delete all related records.

    Also removes local PDF files from storage.
    """
    try:
        await svc.delete_claim(claim_id, db)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc))
    except Exception as exc:
        logger.error("delete_claim failed | claim_id=%s | %s", claim_id, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to delete claim.",
        )

    return DeleteClaimResponse(
        success=True,
        claim_id=claim_id,
        message="Claim and all related data deleted successfully.",
    )


# ── POST /claims/{claim_id}/documents ─────────────────────────────────────────

@router.post(
    "/{claim_id}/documents",
    response_model=DocumentUploadResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Upload a PDF document for a claim",
)
async def upload_claim_document(
    claim_id: str,
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    claim_svc: ClaimService = Depends(get_claim_service),
    doc_svc: DocumentService = Depends(get_document_service),
) -> DocumentUploadResponse:
    """Upload a PDF document for an existing claim.

    In a single request:
    - Validates claim exists
    - Validates PDF (extension, size, empty, corrupted)
    - Stores file to disk
    - Creates claim_documents record
    - Extracts text (PyMuPDF → EasyOCR fallback)
    - Persists raw_ocr_text and page_count
    """
    # ── Validate claim ────────────────────────────────────────────────────────
    try:
        await claim_svc.get_or_404(claim_id, db)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc))

    # ── Validate file ─────────────────────────────────────────────────────────
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only .pdf files are accepted.",
        )

    file_bytes = await file.read()

    if not file_bytes:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Uploaded file is empty.",
        )

    if len(file_bytes) > _MAX_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File exceeds the maximum allowed size of {settings.MAX_UPLOAD_SIZE_MB} MB.",
        )

    # ── Ingest ────────────────────────────────────────────────────────────────
    try:
        result = await doc_svc.ingest(
            claim_id=claim_id,
            original_filename=file.filename,
            file_bytes=file_bytes,
            db=db,
        )
    except (PDFExtractionError, FileNotFoundError) as exc:
        logger.error("PDF error | claim=%s | file=%s | %s", claim_id, file.filename, exc)
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)
        )
    except OCRError as exc:
        logger.error("OCR error | claim=%s | file=%s | %s", claim_id, file.filename, exc)
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)
        )
    except Exception as exc:
        logger.error("Ingest error | claim=%s | file=%s | %s", claim_id, file.filename, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Document ingestion failed. See server logs.",
        )

    return DocumentUploadResponse(
        success=True,
        claim_id=result.claim_id,
        document_id=result.document_id,
        file_name=result.file_name,
        page_count=result.page_count,
        characters=result.characters,
        extraction_method=result.extraction_method,
        ocr_used=result.ocr_used,
        storage_path=result.storage_path,
        message="Document uploaded and processed successfully.",
    )
